version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./desafio-node/Dockerfile
    container_name: app
    networks:
      - node-network
    volumes:
      - ./desafio-node:/usr/src/app
      - /usr/src/app/node_modules
    command: "dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint"
    tty: true
    # ports:
    #   - "3000:3000"
    depends_on:
      - db

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    restart: always
    networks:
      - node-network
    ports:
      - 8080:80
    depends_on:
      - app

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
    # ports:
    #   - "42333:3306"

networks:
  node-network:
    driver: bridge